FROM python:3.11
RUN apt-get update && apt-get install -y g++ && apt-get install -y gcc
WORKDIR /OJ
COPY . /OJ


RUN pip install --no-cache-dir -r requirements.txt

RUN python manage.py makemigrations
RUN python manage.py migrate
EXPOSE 8000

ENV DJANGO_SETTINGS_MODULE=MYOJ.settings

ENV PYTHONUNBUFFERED=1

CMD ["python","manage.py","runserver","0.0.0.0:8000"]